### PR TITLE
Change 'riterator' to 'itarator' in EvictorBase.java

### PR DESCRIPTION
**Pull request by mkasprz**

### CODE REVIEW

**Comment by sbesson** [comment]
Hi @mkasprz, this repository was originally open to mirror the ZeroC Ice source code but ZeroC now have its own GitHub repository https://github.com/zeroc-ice/ice. Could you reopen this Pull Request against this repository instead. We will deprecate this fork shortly.

**Comment by mkasprz** [comment]
Thanks for answer. I wanted to do what You suggested, but I couldn't find 'EvictorBase' class in that repository. Seems like it just doesn't exist any more.

**Comment by joshmoore** [comment]
On the 3.5 branch, it's there: https://github.com/zeroc-ice/ice/blob/3.5/java/demo/book/evictor/EvictorBase.java

**Comment by mkasprz** [comment]
Huh, thank You. I don't know why 'This repository' search didn't find it for me.

**Pull request closed without merging**
